#!/bin/bash
# SPDX-License-Identifier: Apache-2.0

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi

set -eu
set -o pipefail

DIB_KUBELET_VERSION=${DIB_KUBELET_VERSION:-"1.34.0"}
DIB_KUBELET_URL=${DIB_KUBELET_URL:-"https://dl.k8s.io/release/v${DIB_KUBELET_VERSION}/bin/linux/${ARCH}/kubelet"}
DIB_KUBELET_SHA256SUM_URL=${DIB_KUBELET_SHA256SUM_URL:-"${DIB_KUBELET_URL}.sha256"}

TMPDIR=$(mktemp -d)
trap "rm -rf $TMPDIR" EXIT

# Download and verify
cd ${TMPDIR}
curl -LO $DIB_KUBELET_URL
echo "$(curl -Ls $DIB_KUBELET_SHA256SUM_URL)  kubelet" | sha256sum -c -
install -m 755 kubelet /usr/bin/kubelet

# Configure sysctl values
cat <<EOF > /etc/sysctl.d/99-kubelet.conf
fs.inotify.max_user_instances = 8192
fs.inotify.max_user_watches = 524288
kernel.panic = 10
kernel.panic_on_oops = 1
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
net.ipv4.ip_forward = 1
net.ipv4.tcp_congestion_control = bbr
net.ipv6.conf.all.disable_ipv6 = 0
net.ipv6.conf.all.forwarding = 1
vm.overcommit_memory = 1
EOF

# TODO: make sure no swap?

# Configure services on EL nodes
if [ -f /etc/redhat-release ]; then
    # NOTE(fitbeard): Remove wireless drivers and mask firewalld
    dnf -C -y remove iwl\*
    systemctl mask firewalld
    systemctl disable conntrackd
    systemctl enable chronyd
    systemctl enable auditd
fi

# Enable service
systemctl enable kubelet
