#!/bin/bash
# SPDX-License-Identifier: Apache-2.0

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi

set -eu
set -o pipefail

if [ -f /etc/redhat-release ]; then
    # NOTE(mnaser): The GPG error has been updated but the "elrepo-release" package
    #               still points to the old key.
    rpm --import https://www.elrepo.org/RPM-GPG-KEY-elrepo.org

    dnf install -y elrepo-release
    dnf --enablerepo=elrepo-kernel install -y kernel-${DIB_ELREPO_KERNEL_TYPE}
fi
