#!/bin/bash
# SPDX-License-Identifier: Apache-2.0

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi

set -eu
set -o pipefail

if [ -f /etc/redhat-release ]; then
    rpm --import https://www.elrepo.org/RPM-GPG-KEY-elrepo.org
    dnf install -y https://www.elrepo.org/elrepo-release-${DIB_RELEASE}.el9.elrepo.noarch.rpm

    dnf --enablerepo=elrepo-kernel install -y kernel-${DIB_ELREPO_KERNEL_TYPE}
fi
