#!/bin/bash
# SPDX-License-Identifier: Apache-2.0

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi

set -eu
set -o pipefail

# NOTE(fitbeard): Disable weak dependencies
if [ -x /usr/bin/dnf ]; then
    echo "install_weak_deps=False" >> /etc/dnf/dnf.conf
fi
