#!/bin/bash
# SPDX-License-Identifier: Apache-2.0

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi

set -eu
set -o pipefail

# NOTE(fitbeard): Install newer mainline stable kernel
if [ -f /etc/redhat-release ]; then
    dnf install -y elrepo-release
    dnf --enablerepo=elrepo-kernel install -y kernel-ml
fi
