#!/bin/bash
# SPDX-License-Identifier: Apache-2.0

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi

set -eu
set -o pipefail

DIB_CONTAINERD_VERSION=${DIB_CONTAINERD_VERSION:-"2.1.5"}
DIB_CONTAINERD_URL=${DIB_CONTAINERD_URL:-"https://github.com/containerd/containerd/releases/download/v${DIB_CONTAINERD_VERSION}/containerd-${DIB_CONTAINERD_VERSION}-linux-${ARCH}.tar.gz"}
DIB_CONTAINERD_SHA256SUM_URL=${DIB_CONTAINERD_SHA256SUM_URL:-"${DIB_CONTAINERD_URL}.sha256sum"}

TMPDIR=$(mktemp -d)
trap "rm -rf $TMPDIR" EXIT

# Download and verify
cd ${TMPDIR}
curl -LO $DIB_CONTAINERD_URL
curl -LO $DIB_CONTAINERD_SHA256SUM_URL
sha256sum -c containerd-${DIB_CONTAINERD_VERSION}-linux-${ARCH}.tar.gz.sha256sum

# Extract into /usr/bin
tar --strip-components=1 -C /usr/bin -xvzf containerd-${DIB_CONTAINERD_VERSION}-linux-${ARCH}.tar.gz

# Create folders for configuration
install -d -o root -g root -m 711 /etc/containerd
install -d -o root -g root -m 700 /var/lib/containerd
install -d -o root -g root -m 711 /run/containerd
# NOTE(fitbeard): CVE-2024-25621
install -d -o root -g root -m 700 /run/containerd/io.containerd.grpc.v1.cri
install -d -o root -g root -m 700 /run/containerd/io.containerd.sandbox.controller.v1.shim

# Create containerd config file
containerd config default > /etc/containerd/config.toml

# NOTE(fitbeard): Disable unused snapshotters.
#                 These plugins also prevent 'containerd' from running without proper configuration.
sed -i 's|^disabled_plugins.*|disabled_plugins = ["io.containerd.snapshotter.v1.btrfs","io.containerd.snapshotter.v1.zfs","io.containerd.snapshotter.v1.devmapper","io.containerd.snapshotter.v1.erofs"]|' /etc/containerd/config.toml

# NOTE(mnaser): Ensure SystemdCgroup is enabled.
sed -i 's/SystemdCgroup = false/SystemdCgroup = true/g' /etc/containerd/config.toml

if [ -f /etc/redhat-release ]; then
    # NOTE(fitbeard): Ensure selinux support is enabled
    sed -i 's/enable_selinux = false/enable_selinux = true/g' /etc/containerd/config.toml

    # NOTE(mnaser): 'diskimage-builder' does not support conditional
    #               element dependencies, so we cannot use the
    #               'selinux-permissive' element.
    echo "SELINUX=permissive" > /etc/selinux/config
    echo "SELINUXTYPE=targeted" >> /etc/selinux/config
fi

# Enable service
systemctl enable containerd
