#!/bin/bash
# SPDX-License-Identifier: Apache-2.0

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi

set -eu
set -o pipefail

# NOTE(fitbeard): Make sure /etc/kubernetes/manifests dir exists.
mkdir -p /etc/kubernetes/manifests
